version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    container_name: erudite_api

  erudite_pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: erudite
    container_name: erudite_pg
    ports:
      - "35432:5432"
    volumes:
      - erudite_pg_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  erudite_pg_data: